
[build]
  base    = "project/"
  publish = "project/build-output/"
  command = "echo 'default context'"
  ignore = "git diff --quiet HEAD^ HEAD sub_dir/"

[[redirects]]
  from = "/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  query = {path = ":path"} 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://us-central1-netlify-intercom.cloudfunctions.net/readHeaders/:splat"
  status = 200


[[headers]]
  for = "/*" 
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"